#!/usr/bin/env bash
# Render zones/*.yaml OctoDNS YAML into dnsmasq address= overrides.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUT="${ROOT_DIR}/config/dnsmasq/generated-hosts"
ZONES_DIR="${ROOT_DIR}/zones"

python3 - "$ZONES_DIR" "$OUT" <<'PY'
import glob
import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML required: pip install pyyaml\n")
    sys.exit(1)

zones_dir, out_path = sys.argv[1], sys.argv[2]
lines = [
    "# Generated by deploy/compose/scripts/generate-dnsmasq-hosts.sh — do not edit",
    "10.89.3.99 edge-local.robust-dns.lab",
]

for path in sorted(glob.glob(os.path.join(zones_dir, "*.yaml"))):
    zone = os.path.basename(path).removesuffix(".yaml")
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    for name, rec in data.items():
        if not isinstance(rec, dict):
            continue
        rtype = rec.get("type", "")
        values = rec.get("values") or []
        if rtype not in ("A", "AAAA") or not values:
            continue
        if name in ("", None):
            fqdn = zone
        else:
            fqdn = f"{name}.{zone}"
        lines.append(f"{values[0]} {fqdn}")

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"Wrote {out_path} ({len(lines) - 2} zone records)")
PY
