-- dnsdist authoritative front-end — PoP EU (anycast profile)
-- Binds anycast VIP; backends are local secondary only.

setLocal("10.89.99.53:53")
setLocal("0.0.0.0:5300")

newServer({
  address = "10.89.4.12:53",
  name = "pdns-pop-eu",
  checkType = "A",
  checkName = "ns1.infra.5g-deployment.lab.",
  checkInterval = 10,
  maxCheckFailures = 3,
  rise = 2
})

setServerPolicy(firstAvailable)

addACL("10.89.0.0/8")
addACL("127.0.0.0/8")
addACL("::1/128")

webserver("0.0.0.0:8083")
