# BIRD — PoP US (profile anycast)
router id 10.89.5.20;

protocol device {
}

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 {
    import all;
    export all;
  };
}

protocol static anycast_vip {
  ipv4;
  route 10.89.99.53/32 via "lo" {
    bfd on;
  };
}

protocol bgp rr {
  local 10.89.5.20 as 65005;
  neighbor 10.89.6.1 as 65000;
  ipv4 {
    import all;
    export filter {
      if net = 10.89.99.53/32 then accept;
      reject;
    };
  };
}
